# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ReactNativeGRPCExample' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeGRPCExample

  target 'ReactNativeGRPCExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ReactNativeGRPCExampleTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'ReactNativeGRPCExample-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ReactNativeGRPCExample-tvOS

  target 'ReactNativeGRPCExample-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
