# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RNReactNativeGrpc' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RNReactNativeGrpc
  pod 'react-native-grpc-glife', :path => '.'
  pod 'DoubleConversion', :podspec => '../react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../react-native/third-party-podspecs/Folly.podspec'
  pod 'yoga', :path => '../react-native/ReactCommon/yoga'
  pod 'React', :path => '../react-native', :subspecs => [
      'Core',
      'CxxBridge', # Include this for RN >= 0.47
      'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
      'RCTText',
      'RCTNetwork',
      'RCTWebSocket', # Needed for debugging
      'RCTAnimation', # Needed for FlatList and animations running on native UI thread
      # Add any other subspecs you want to use in your project
  ]
end
